### ISSUE TITLE
snappyHexMesh Component Fatal Error: Point not inside the mesh or on a face or edge when file in meters

### ISSUE THREAD

**Issue by ajakubiec** [mostaphaRoudsari/Butterfly#94] opened 2016-10-14 01:13 UTC
Hi Mostapha, all,

I'm testing out the outdoor_airflow example.gh file and run into some errors at the snappyHexMesh component stage when running the reconstructParMesh -constant command.
`[2] --> FOAM FATAL ERROR: [1] Point (15.72323 63.68281 14.12629) is not inside the mesh or on a face or edge.
 Bounding box of the mesh:(-2.413212 -3.699739 0) (12.00438 42.54625 8.617038)`

I tracked this down to the "convertToMeters 0.3050;" line which is written into C:\Users*\butterfly\outdoor_airflow\system\blockMeshDict. The created mesh is scaled down despite that my file is in meters. I just edited the blockMeshDict file to read "convertToMeters 1.0;" and re-ran the batch file manually. Voila -- working solution. I tried to hack the writing of '1.0' into my blockMeshDict.py file, but to no avail so far.

Thanks for the work on this!
Alstan

**Comment by TheodoreGalanos** [comment] 2016-10-14 03:29
Hi @ajakubiec 

Thanks for reporting. This is a weird one indeed, I don't remember us messing with the convertToMeters value. Perhaps something happened in the update messed it up.

I'm sure Mostapha will make quick work of this :)

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment] 2016-10-14 12:09
Hi Alstan and Theodore,

Alstan, thank you for reporting this. Isn't the document units in Feet in your case? Butterfly [sets up the conversation](https://github.com/mostaphaRoudsari/Butterfly/blob/634fd8b53b908503ee52a0de33ffbff9b9a5c751/butterfly/gh/unitconversion.py#L20-L21) based on Rhino units. Are you sure that the document units are in meters?

In any case, that looks like a bug. Let me check and get back to you as soon as I can.

**Comment by ajakubiec** [comment] 2016-10-14 13:24
I am almost certain my model was in meters, but I was working from an untitled Rhino file, if that makes a difference. I can check next time I am at work.

**Comment by avarth** [comment] 2016-10-15 06:27
I also came across the same issue last week when trying to test the example files. Check if your default untitled Rhino file is in meters. Mine was in millimeters and the problem persisted even after I changed the units to meters. The issue is resolved (at least for me) by making a new untitled Rhino file in meters (large objects).

**Comment by mostaphaRoudsari** [comment] 2016-10-15 15:03
@avarth thank you for the input. Very helpful. I checked the unit conversion. Butterfly doesn't cache the value for units. I think it happens because of the order of writing the files in Butterfly. For now re-calculating the Grasshopper script should solve the problem. I'm adding a unit check to blockMesh and snappyHexMesh to modify blockMeshDict and In if the unit has changed.

Here is what I think happens:
Once you open the grasshopper file wind tunnel component writes all the files to the folder including blockMeshDict. The component is not aware of the unit change in Rhino so the file doesn't get updated.  Then when you run snappyHexMesh the component sets `locationInMesh` to the center of the boundingbox based on the updated units! Will add an extra check and this should be fixed.

**Closed** 2016-10-31 12:02 UTC
Labels: bug, critical, grasshopper
