### ISSUE TITLE
Runtime error: Failed to find container id.

### ISSUE THREAD

**Issue by chokhachian** [mostaphaRoudsari/Butterfly#43] opened 2016-07-17 19:13 UTC
I have this error when I try to run Block mesh component, I try to run start_OF.bat file but still did not solve...

![untitled](https://cloud.githubusercontent.com/assets/13383931/16902571/f32fb144-4c62-11e6-9b67-f92d69a9f79c.jpg)

**Comment by mostaphaRoudsari** [comment] 2016-07-17 22:47
@chokhachian thank you for trying butterfly. Can you send a screenshot of the container. As far as I can see in your screen capture there is no open batch file. It should look like the screenshot below.

![image](https://cloud.githubusercontent.com/assets/2915573/16903511/c6cf4844-4c4e-11e6-9339-b046a96d70ca.png)

**Comment by chokhachian** [comment] 2016-07-18 18:08
@mostaphaRoudsari Dear Mostapha, Thanks for the reply
I get some errors in the first steps of running OpenFoam!
![1](https://cloud.githubusercontent.com/assets/13383931/16925160/31c33852-4d23-11e6-92d6-5db302bfed3c.jpg)

**Comment by mostaphaRoudsari** [comment] 2016-07-18 18:23
@chokhachian that's something that you need to get fixed before trying butterfly. Have you checked online resources to fix the issue. In your case it looks like the powershell didn't get installed correctly.

**Comment by chokhachian** [comment] 2016-07-18 19:44
@mostaphaRoudsari seems on windows10 it works with latest version of openFOAM

**Comment by mostaphaRoudsari** [comment] 2016-07-18 20:08
@chokhachian I see. then we probably need to test the butterfly against the  latest version of butterfly. I'm traveling for a couple of weeks but that will be on top of the list once I'm back. Thank you for testing.

**Comment by chokhachian** [comment] 2016-07-18 20:18
@mostaphaRoudsari I already installed of_plus_1606 version and working with no errors, also tried to modify the runmanager.py file but couldn`t get through it, it needs your magic hands

**Comment by TheodoreGalanos** [comment] 2016-07-21 05:56
@chokhachian Thanks for testing! Glad to see you made it work with the new version, it's something we will test the coming weeks as well.

Please keep coming with any issues you might have with the practical side as well. Thanks!

**Comment by TheodoreGalanos** [comment] 2016-07-22 09:07
@mostaphaRoudsari 
I seem to have difficulty linking to v1606 as well. OF is running but butterfly cannot see it. Probably a matter of updating the run component?

![of_v1606_butterfly](https://cloud.githubusercontent.com/assets/13436572/17052134/bbf7753e-502e-11e6-9def-af6c4f12bcc9.png)

**Comment by mostaphaRoudsari** [comment] 2016-07-27 09:27
@chokhachian @TheodoreGalanos finally installed the latest version. Now the package is using a newer Docker technology which is actually a great news. Eventually it makes everything easier for us. I need more time to implement changes for the new version but I put it on top of the list. We will make sure to have this ready before the first public release.

**Comment by sufia89** [comment] 2016-08-08 08:08
Hi mostapha
thanks for your useful plugins
I have the same problem like the first comment and can't understand how to solve it ... does it have a solution at last ??

**Comment by SaraAghaC** [comment] 2016-08-08 09:34
Hi mostapha
Thanks a lot for your new plugin
I have a same problem like a first comment and can't understand weather or not it has solved ?

**Comment by mostaphaRoudsari** [comment] 2016-08-09 17:31
Butterfly should now work with the latest version of OpenFOAM. To update your installation use butterfly component and set update_ to True.

![image](https://cloud.githubusercontent.com/assets/2915573/17526320/b62ff3c4-5e34-11e6-9cc0-8700fa21b544.png)

Once it is done close **both Grasshopper and Rhino** and open a new Rhino and Grasshopper. Butterfly component should be updated to version 0.0.02 and should work fine with latest version of OpenFOAM. Just open one of the old sample files and try to run the analysis.

![image](https://cloud.githubusercontent.com/assets/2915573/17526436/4443e008-5e35-11e6-94e5-176e6038dc7e.png)

Let me know if you had any issues.

**Comment by Omidmr** [comment] 2016-08-09 18:51
Hi @mostaphaRoudsari ,
Many thanks for fix & update the newer version of butterfly.
Butterfly is now Run fine in windows 10 and compatible with latest version of Openfoam!

![tnx](https://cloud.githubusercontent.com/assets/11173265/17528955/b7bd80ba-5e86-11e6-986b-c38290981b2f.png)

Thanks again,
-Omid

**Comment by mostaphaRoudsari** [comment] 2016-08-09 18:53
@Omidmr nice! thanks for testing and letting me know.

**Comment by timera** [comment] 2016-09-05 23:22
Hi! I am having the same issue, I have downloaded the most up-to-date openFOAM, and butterfly build. The only difference for me is that I am running Windows 7. Could you help me with this situation?
<img width="957" alt="capture" src="https://cloud.githubusercontent.com/assets/5554550/18258119/ff73544e-739d-11e6-80ca-19ab8d840b77.PNG">

**Comment by malshayeb** [comment] 2016-09-20 22:23
Hi,

I've tried Butterfly with windows 7 and I got an error. I have the latest version of OF. 
![2](https://cloud.githubusercontent.com/assets/20121973/18690994/dda56eb4-7f56-11e6-8694-4a0447512284.png)

Also, I test it with windows 10 and did not run too.
![1](https://cloud.githubusercontent.com/assets/20121973/18691028/fd00ec02-7f56-11e6-958e-2a100e60d8bb.png)

**Comment by mostaphaRoudsari** [comment] 2016-09-20 22:38
@timera a couple of users have reported a similar issue on Windows 7.  The issue is that butterfly can't run the batch file that gets the id of the container and so it assumes you don't have the container running. I need to add some alternate methods to address this. At the same time, I assume if we can't get the issue fixed with running batch files, you won't be able to run the analysis anyways.

@malshayeb, in your case as far as I can see the installation of OpenFOAM has failed in both cases. You can see the error messages in cmd. Can you try to uninstall and re-install OpenFOAM and try again?

**Comment by timera** [comment] 2016-09-21 17:56
@mostaphaRoudsari , thanks for addressing the issue, let me know when it has been resovled

thanks,
Tim

**Comment by malshayeb** [comment] 2016-10-02 22:53
Thank you Mostapha,

Yes, I reinstalled OF on Windows 10 and It worked fine but then I got an issue. 
![1](https://cloud.githubusercontent.com/assets/20121973/19024431/b3e694ea-88c0-11e6-88cd-c066f0c8f0a0.png)

**Comment by mostaphaRoudsari** [comment] 2016-10-02 23:40
@malshayeb can you try [this suggestion](https://github.com/mostaphaRoudsari/Butterfly/issues/49#issuecomment-242086814)? It has worked on Windows 10 for other users.

**Comment by TheodoreGalanos** [comment] 2016-10-13 05:50
Is this issue closed by now? Or do we at least know the reasons behind it right?

If it's not yet closed, I was wondering if it is worth trying to connect BF with OpenFoam 4.0 and see how it reacts.

**Comment by mostaphaRoudsari** [comment] 2016-10-13 14:14
@TheodoreGalanos it's an issue with Windows. What I will do next is to use docker python API to run the commands instead of using batch files and subprocess. That might help.

**Comment by mostaphaRoudsari** [comment] 2016-10-13 14:28
@houmanparhizkar4848 does blockMesh and snappyHexMesh run fine on your machine? If that is the case, it's a different issue from this one.

**Comment by houmanparhizkar4848** [comment] 2016-10-13 20:16
@mostaphaRoudsari guess they are working fine ... 
but I dont know why does nothing happen to Openfoam starter while grasshopper components are activated .. 
I dont know how to fix it :) 
![untitled](https://cloud.githubusercontent.com/assets/22817901/19365335/1edb476e-919f-11e6-871c-585eec966176.png)

**Comment by mostaphaRoudsari** [comment] 2016-10-31 18:35
All, I re-wrote `runmanager` class and get rid of batch files. Can you update to version 0.0.03 and the new example files and let me know if it has solved the problem?

**Comment by mostaphaRoudsari** [comment] 2016-10-31 20:31
[Here are the directions to install version 0.0.03](https://github.com/mostaphaRoudsari/Butterfly/issues/100#issuecomment-257411326). The old installer won't work!

**Comment by amirmakan** [comment] 2016-11-22 05:15
The same problem.
I tried BlueCFD too: [www.bluecape.com.pt/blueCFD-Core](www.bluecape.com.pt/blueCFD-Core)
but it doesn't have web service

there are many red errors
what is login root & password for OpenFoam?

**Comment by mostaphaRoudsari** [comment] 2016-11-22 20:14
@Omidmr Butterfly is not designed to work with blueCFD. You can find the correct links here.

I'm closing this issue as the recent changes seems to have solved the problem for standard OpenFOAM installation.

**Closed by mostaphaRoudsari** 2016-11-22 20:14 UTC
Labels: bug, critical

**Comment by vansicek** [comment] 2016-11-24 17:15
Hello, thanks Mostapha and team for such a great tool. 

I am getting an issue that @malshayeb also seemed to get (see image below). I did a little checking, and I'm thinking it might be a problem with Docker not allowing uppercase letters in the workingdir path. This seems ridiculous though; has anyone else had this issue? Thanks!

<img width="426" alt="capture" src="https://cloud.githubusercontent.com/assets/6708598/20606536/34da5d94-b237-11e6-961d-c7d871b738c1.PNG">

**Comment by andrear4568** [comment] 2017-01-11 16:41
Hello @vansicek I have the same issue, have you solved it?

**Comment by mimarilker** [comment] 2017-01-11 18:16
I advise you to make a clean istall. Follow the instructions in the attached link and let us know if it works.

https://github.com/ladybug-analysis-tools/butterfly/wiki/Windows-10-Installation-Notes

**Comment by mimarilker** [comment] 2017-01-11 18:17
I advise you to make a clean install. Follow the instructions in the attached link and let us know if it works.

https://github.com/ladybug-analysis-tools/butterfly/wiki/Windows-10-Installation-Notes
